import { registerEnumType } from '@nestjs/graphql';

export enum TaskType {
  SHIFT_BELOW_MINIMUM = 'SHIFT_BELOW_MINIMUM',
  SHIFT_APPROVAL = 'SHIFT_APPROVAL',
  EVENT_APPROVAL = 'EVENT_APPROVAL',
  CONTRACT_SIGN = 'CONTRACT_SIGN',
  TIMESHEET_SIGN = 'TIMESHEET_SIGN',
  TIMESHEET_BUNDLES = 'TIMESHEET_BUNDLES',
  DOCUMENT_DECLINED = 'DOCUMENT_DECLINED',
  CONTRACT_EXPIRING = 'CONTRACT_EXPIRING',
  MEMBERSHIP_REQUEST = 'MEMBERSHIP_REQUEST',
}

registerEnumType(TaskType, {
  name: 'TaskType',
});
